db:  
  image: postgres
redis:
  image: redis
pace-app:  
  build: .
  ports:
    - "3000:3000"
  links:
    - db
    - redis
  environment:
    - DATABASE_URL=postgres://db:5432/postgres
    - PGHOST=db
    - PGDATABASE=postgres
    - PGUSER=postgres
    - REDISHOST=redis
