# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "wegtam/db-tester"
  config.vm.network :forwarded_port, guest: 5432, host: 5432
  config.vm.network :forwarded_port, guest: 6379, host: 6379
  config.vm.provision "shell",
      inline: "su vagrant -c 'psql postgresql://sa:vagrant@localhost/postgres -c \"create database pace with owner=sa;\"'"
  config.vm.provision "file", source: "redis.conf", destination: "/tmp/redis.conf"
  config.vm.provision "shell", inline: "apt-get update; apt-get -y install redis-server"
  config.vm.provision "shell", inline: "cp /tmp/redis.conf /etc/redis/redis.conf; /etc/init.d/redis-server restart"
end
